# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- dev

pool:
  vmImage: 'ubuntu-24.04' 

resources:
- repo: self

variables:
  tag: '$(Build.BuildNumber))'

stages:
- stage: Docker
  displayName: Build and push Docker image
  jobs:
  - job: Docker build and push
    displayName: Build and push Docker image
    steps:
    - task: Docker@2
      displayName: Build Docker image
      inputs:
        command: build
        dockerfile: './Dockerfile'
        tags: $(tag)
    - task: Docker@2
      displayName: Log in to ACR
      inputs:
        command: login
        containerRegistry: acr-morphic
    - task: Docker@2
      displayName: Push docker image
      inputs:
        command: push
        containerRegistry: acr-morphic
        tags: $(tag)
    - task: Docker@2
      displayName: Log out of ACR
      inputs:
        command: logout
        containerRegistry: acr-morphic
